name = "Schrodingy"
uuid = "f939b1b8-4172-47c8-a2af-6a98ac294924"
authors = ["Gregory Wagner <gregory.leclaire.wagner@gmail.com>"]
version = "0.1.0"

[deps]
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
